### ISSUE TITLE
Move ALL strings into the strings.xml

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/MetadataRemover#28]
What do you think about moving [all strings](https://developer.android.com/guide/topics/resources/localization#move-strings-xml) into the [strings.xml](https://github.com/Crazy-Marvin/MetadataRemover/blob/development/app/src/main/res/values-en-rUS/strings.xml) instead of using several files?

![strings](https://user-images.githubusercontent.com/15004217/178324649-45fb1072-4a72-41fa-896d-6e4625227138.JPG)

This should make translation easier, shouldn't it?

**Comment by janheinrichmerker** [comment]
I think it doesn't really matter in terms of translatability. You can upload multiple files on any translation platform I know of.
So I would rather keep them separate to have some high-level categorization. E.g., we don't change the strings of the "About" activity very often. But in a Git commit it might be useful to see, only strings from the metadata attributes changed.
But of course that's personal taste. I can merge the files if you think otherwise.

**Comment by CrazyMarvin** [comment]
> I think it doesn't really matter in terms of translatability. You can upload multiple files on any translation platform I know of. So I would rather keep them separate to have some high-level categorization. E.g., we don't change the strings of the "About" activity very often. But in a Git commit it might be useful to see, only strings from the metadata attributes changed. But of course that's personal taste. I can merge the files if you think otherwise.

I see your point but please merge all strings into a single strings.xml please.

**Comment by janheinrichmerker** [comment]
Will do
